name: just
title: just (by casey)
base: core24
version: 1.38.0
summary: 🤖 Just a command runner.
description: |
  just is a handy way to save and run project-specific commands. 
  Commands, called recipes, are stored in a file called justfile with syntax inspired by make.

grade: stable
confinement: classic

platforms:
  amd64:
  arm64:
    build-on: ["amd64", "arm64"]
    build-for: ["arm64"]

parts:
  just:
    plugin: rust
    source: https://github.com/casey/just.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    organize:
      just: bin/just
    build-environment:
      - to amd64:
        - CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu
      - to arm64:
        - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        - CARGO_BUILD_TARGET: aarch64-unknown-linux-gnu
        - CC: aarch64-linux-gnu-gcc
    build-packages:
      - to amd64:
        - mingw-w64
      - to arm64:
        - gcc-aarch64-linux-gnu
        - linux-libc-dev-arm64-cross
        - libc6-dev-arm64-cross
    build-attributes:
      - enable-patchelf
    override-build: |
      rustup target add $CARGO_BUILD_TARGET
      RUSTFLAGS="--codegen target-feature=+crt-static" cargo build --target $CARGO_BUILD_TARGET --release
      install -Dvm755 target/$CARGO_BUILD_TARGET/release/just "${CRAFT_PART_INSTALL}"

apps:
  just:
    command: bin/just
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
