name: Pull Request

on:
  pull_request:


jobs:
  test:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get snap version
        id: get-version
        run: |
          sudo snap install yq
          snap_version=$(yq .version snap/snapcraft.yaml)
          echo "snap_version=$snap_version" >> $GITHUB_OUTPUT
      - name: Build snap
        id: build
        uses: canonical/action-build@v1
      - name: Install snap (test)
        run: |
          sudo snap install --dangerous --classic ${{ steps.build.outputs.snap }}
          just --version  # Make sure that just is working
          just_version=$(just --version)
          if [[ "$snap_version" != "$just_version"]]; then
            echo "The snap version differs from the Just version!"
            echo "snap ($snap_version) != just ($just_version)"
            exit 1
          fi
